### ISSUE TITLE
Ajout d'items depuis le catalogue, après sélection de la box "Sur-mesure"

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#10]
@Wonsy 

L'ajout d'items est à intégrer sur le même modèle que figma (section "CATALOGUE")

L'usager ne peut ajouter que 4 items à son panier, pas plus.
Le bouton "commander" n'est accessible qu'après sélection de 4 items.

**Comment by Wonsy** [comment]
@yowamuzadi : Vu; en attente de MEP.
