### ISSUE TITLE
Mails de commande

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#11]
@Wonsy 
Quand l'utilisateur passe commande : il reçoit un mail de confirmation pour lui annoncer que sa commande a été validée et qu'il va recevoir la box dans les prochains jours .
Quand l'utilisateur reçoit sa box en point relais/chez lui : il reçoit un mail d'information pour lui annoncer.
Quand une commande est passé pour une livraison en point relais : Le RDLC reçoit un mail pour le prévenir de la commande et pour qu'il puisse la préparer.

(cf. contenu mail > https://trello.com/c/SKoSOJKw/171-pr%C3%A9parer-des-mails-types-pour-la-commande).

**La partie UI des 3 mails a été réalisé sur le Figma, dans le dossier "Mails".**

**Comment by PerrineG** [comment]
@Wonsy : Hello, comme discuté hier, j'ai ajouté dans le fichier Figma, les 4 visuels des box à intégrer dans les mails.

**Comment by Wonsy** [comment]
En production.
