### ISSUE TITLE
Gestion des envois automatiques des questionnaires de satisfaction

### ISSUE THREAD

**Issue by ViMotte** [SocialGouv/tumeplay-app#110]
Mettre en place l'envoi automatique, 28 jours après une commande, d'un mail qui invite l'utilisateur à répondre à notre questionnaire de satisfaction.

**Comment by yowamuzadi** [comment]
Pour préciser, il s'agit du questionnaire de satisfaction sur les box :)
Est-ce que cet enhancement est prévu pour bientôt ?

**Comment by PerrineG** [comment]
Il s'agit du questionnaire : https://forms.gle/79mL7e1t33T9nMvD6
