### ISSUE TITLE
Commande de box ou produits non disponibles

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#13]
Si une box n'est pas disponible lors de la commande (par exemple la box 3 qui ne sera pas prête pour le lancement), alors il faut griser sa card afin qu'elle ne soit pas sélectionnable. > _À discuter avec l'équipe : laisse-t'on l'utilisateur accéder au contenu de la box afin qu'il sache ce qu'il y aura dedans mais le bouton de commande est grisé et il y a un petit texte explicatif au dessus ?_
De même pour un produit, si pour X raison, le RDLC n'a plus ce produit il faut l'afficher de la même manière.

**Voir la proposition d'UI sur le fichier Figma où il y a tous les écran > partie "Catalogue".**

**Comment by Wonsy** [comment]
En attente MEP.

**Comment by Wonsy** [comment]
En production.
