### ISSUE TITLE
feat: Ajout sentry

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/tumeplay-app#14]
Ajouter le tracking des erreurs sentry

https://sentry.fabrique.social.gouv.fr/incubateur/tumeplay/

DSN : https://58c382a0f5bb4e11be31887a0920aa8d@sentry.fabrique.social.gouv.fr/33

un exemple d'implem est dispo sur : https://github.com/SocialGouv/sample-next-app

**Comment by Wonsy** [comment]
En production.
