### ISSUE TITLE
Erreur parcours. Écran fin de quiz < 1000 points et -25 ans

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#19]
Quand j'ai moins de 25 ans et moins de 1000 points, je n'ai pas accès à la commande de boîtes. 

Pourtant dans ce cas, l'écran gain de points affiche tout de même :
"Bravo ! Tu as gagné assez de points pour commander ton cadeau gratuitement !" 
sauf que ce n'est pas le cas. 

L'écran à afficher dans ce cas est dans figma, partie "questionnaires".

**Comment by Wonsy** [comment]
Bien reçu / vu, en attente de MEP.
