### ISSUE TITLE
Intégration des points relais dans la carte Mondial Relay

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#20]
Seuls les points relais près de gare du Nord s'affichent... c'est problématique sachant que nos territoires d'expérimentation sont en priorité : 
- La Seine-et-Marne
- La métropole bordelaise
- Le lot-et-Garonne

et plus largement il faut **au moins** tous les points relais d'IDF et tous les points relais de Nouvelle-Aquitaine.

**Comment by Wonsy** [comment]
Bonjour Yowa,

Effectivement, le backend est encore en mode "test" : le passage en mode "réel" est prévu pour le prochain déploiement / MEP ( à priori aujourd'hui ).

Restant à disposition,
