### ISSUE TITLE
Back-office. Gestion du stockage

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#22]

**Comment by ViMotte** [comment]
Dans espace Produit du BO :
 - Ajouter une colonne "Disponible à la commande" -> checkbox
 - Ajouter une colonne "Quantité restante" -> valeur décrémentée à mesure que les produits sont commandés (à afficher en bold + red lorsque le seuil bas est atteint)
 - Ajouter un bouton "Recommander" -> ouvre une modale avec textfield pour renseigner la quantité souhaitée + bouton "Commander" pour l'envoi d'un bon de commande au partenaire concerné (certainement par mail - à définir pour chaque)

Dans l'espace Notification du BO : 
 - Lever une alerte automatiquement en cas d'un seuil bas atteint sur l'un des produits

A définir : Méthode de calcul du seuil bas

**Comment by Wonsy** [comment]
MEP en cours.
