### ISSUE TITLE
Pages statiques : "conformité"

### ISSUE THREAD

**Issue by ThomasMenant** [SocialGouv/tumeplay-app#23]
Hello

Comme discuté :

- [ ] une page statique "Mentions légales" : https://gist.github.com/ThomasMenant/4fa68d8ec0ba7d5d5ed03b84786e6c69
- [ ] une page statique "Charte" : https://gist.github.com/ThomasMenant/1365a25c2cda039dbb49cf6eda77a81d

La page charte pourra être enrichie au fur et à mesure.

**Comment by Wonsy** [comment]
Prêt à MEP.
