### ISSUE TITLE
Slide catégories

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#24]
@Wonsy :
Pour que l'utilisateur comprenne qu'il faut slider pour accéder aux autres catégories, on peut ajouter une icône "..." à la fin de la ligne (cf. fichier Figma "gabarit / rubrique / catégories test").

_Bonus : Nous avons remarqué en test utilisateur que les catégories ne sont jamais vues car il•elle scroll directement dans le contenu. Est-ce possible de rendre ces catégories en fixe afin qu'il soit toujours visible sur l'écran ?_

**Comment by Wonsy** [comment]
En attente de MEP.

**Comment by Wonsy** [comment]
En production.
