### ISSUE TITLE
[Back-office] Web-service Mondial Relay

### ISSUE THREAD

**Issue by ThomasMenant** [SocialGouv/tumeplay-app#25]
Contexte : 
Pour terminer la commande, il faudrait pouvoir "créer" la commande chez MR, puis éditer/récupérer l'étiquette.

L'idée est de stocker le tout en BO pour permettre des envois complet pour la réalisation/expédition des boites. 

La doc est là : https://www.mondialrelay.fr/media/108937/Solution-Web-Service-V5.6.pdf
Il s'agit de récupérer l'étiquette à imprimer : format 10x15 / poids 600g

En back-office, on doit pouvoir envoyer un mail avec (en lien / en pj) l'étiquette correspondant à la commande.

**Comment by yowamuzadi** [comment]
Ajouter comme expéditeur : 

TUMEPLAY
106 boulevard Richard-Lenoir
75011 Paris

**Comment by Wonsy** [comment]
En production.
