### ISSUE TITLE
Règle d'obtention des badges

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#3]
@Wonsy 
Si j'ai entre 1000 points et 1999 points, le badge "Bienvenue" se débloque
Si j'ai entre 2000 points et 2999 points, le badge "Bébé chat" se débloque
Si j'ai entre 3000 points et 3999 points, le badge "Chaton un peu féroce" se débloque
Si j'ai plus de 4000 points, le badge "Thug cat"  se débloque

**Comment by Wonsy** [comment]
@yowamuzadi : Vu, en attente de MEP.

**Comment by Wonsy** [comment]
Mise en production effectuée.
