### ISSUE TITLE
App > Inversion entre contenu / catégorie dans Les premières fois, Découvre ton corps

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#33]
Le problème dans Explore ta sexualité a été fixé mais il est apparu pour : 
- Les premières fois
- Découvre ton corps

**Comment by yowamuzadi** [comment]
@Wonsy,  

Dans la thématique "Les premières fois", les contenus dans la catégorie "WTF" devraient apparaître dans la catégorie "Sexploration", et les contenus dans la catégorie "Sexploration" devraient apparaître dans la catégorie "WTF"

Dans la thématique "Découvre ton corps", les contenus dans la catégorie "WTF" devraient apparaître dans la catégorie "Sexploration" et les contenus dans la catégorie "Sexploration" devraient apparaître dans la catégorie "WTF"

**Comment by Wonsy** [comment]
Déployé.
