### ISSUE TITLE
Règles d'obtention des points

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#4]
@Wonsy 
Si je réponds à une question et que la réponse est mauvaise (n'est pas bonne), alors j'obtiens 50 points
Si je réponds à une question et que la réponse est bonne, alors j'obtiens 100 points

**Comment by Wonsy** [comment]
@yowamuzadi : Vu, en attente de MEP.

**Comment by Wonsy** [comment]
Mise en production effectuée.
