### ISSUE TITLE
Limiter les envois aux zones disponibles

### ISSUE THREAD

**Issue by ViMotte** [SocialGouv/tumeplay-app#41]
Avant de trouver la bonne approche pour récupérer la localisation de l'utilisateur, il faut limiter l'envoi des box aux zones géographiques prédéfinies : 
 - Indiquer sur la page d'onboarding du quiz (lorsqu'on demande l'âge de l'utilisateur) que la livraison de box est uniquement disponible en Seine-et-Marne (et mettre le nom plutôt que "77") et en région Nouvelle-Aquitaine
 - Indiquer à l'étape 1 de la livraison de commandes (sélection domicile ou point relay) le même message d'information
 - Ne pas permettre à un utilisateur qui renseigne une adresse en dehors de la liste de départements  (check du code postal avant validation) de terminer sa commande et l'emmener vers une page du type "Tu habites en dehors de notre zone de livraison, mais patience, nous arriverons bienôt dans ta région !". -> @PerrineG : Peux-tu en faire un visu sur Figma ?

Pour rappel, liste des départements disponibles : Seine-et-Marne (77), Charente (16), Charente-Maritime (17), Corrèze (19), Creuse (23), Dordogne (24), Gironde (33), Landes (40), Lot-et-Garonne (47), Pyrénées-Atlantiques (64), Deux-Sèvres (79), Vienne (86), Haute-Vienne (87)

**Comment by PerrineG** [comment]
@Wonsy : Voici les 2 écrans (avec l'info de région et département dispo au début du quiz et lors de la saisi du CP à la commande).
<img width="376" alt="Capture d’écran 2020-02-21 à 10 55 54" src="https://user-images.githubusercontent.com/59702865/75023926-e4496980-5498-11ea-90c2-5073526577ca.png">
<img width="376" alt="Capture d’écran 2020-02-21 à 10 53 52" src="https://user-images.githubusercontent.com/59702865/75023951-edd2d180-5498-11ea-8ed0-c869ad894a73.png">
