### ISSUE TITLE
Bug : ouverture et fermeture de la card réponse dans les quiz.

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#48]
@Wonsy :
Petit bug pour afficher les réponses aux quiz.
En cliquant sur "+ d'info" il ne se passe rien. On doit cliquer sur la card pour la déplier. De même pour la refermer.
Est-il possible de modifier ce comportement, afin que l'action se passe au clic sur le bouton "+ d'info" ?

Merci.

**Comment by Wonsy** [comment]
@PerrineG : Bien reçu; il s'agissait du calque du bouton "Suivant" qui passait "au dessus" du "Refermer" selon la hauteur de l'écran utilisé; ça devrait être réglé sur la prochaine livraison.

Restant à disposition,
