### ISSUE TITLE
Bug : Question du quiz avec taille plus petite que les autres

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#49]
@Wonsy :
Dans les quiz, les questions sont dans des cards similaire. Mais une des questions : "C'est quoi une IST ?" s'affiche dans une card plus petite. 
D'où vient le soucis ? Est-ce que c'est possible de la mettre au même format que les autres ?

**Comment by Wonsy** [comment]
@PerrineG : Bien reçu; un point cependant : la largeur de la box est déterminée par la question en elle même, avec une largeur maximale prédéfinie.

Dans le cas présent, la box s'affiche en moins large car elle ne nécessite pas de l'être plus : la question "rentre" dans la zone allouée.

Nous pouvons si tu le souhaites assigner une taille fixe à ces modales, avec un risque pour les écrans à faible largeur ( risque de modale qui "déborde" de l'écran ).

Restant à disposition,

**Comment by Wonsy** [comment]
( Suppression du libellé "bug" : c'est un "work as intended", pas d'anomalie sur ce point )
