### ISSUE TITLE
Règle de déblocage pour la commande des boîtes

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#5]
@Wonsy 
Pour commander une boîte, il faut au minimum 1000 points. 
Chaque boîte commandée entraîne le retrait de 1000 points par boîte. 
Je n'ai pas accès à la commande de boîtes si j'ai moins de 1000 points (écran à concevoir côté UI).

**Comment by Wonsy** [comment]
@yowamuzadi : Vu; c'est effectivement déjà le cas. En attente de l'UI pour mise en place de l'écran.

**Comment by yowamuzadi** [comment]
ok je vois ça avec Perrine :)

**Comment by PerrineG** [comment]
@Wonsy : L'écran "j'ai moins de 1000 points", a été ajouté à Figma, dans la partie "User flow - landing".
<img width="375" alt="Capture d’écran 2020-01-28 à 10 09 42" src="https://user-images.githubusercontent.com/59702865/73250050-61ddca80-41b6-11ea-8149-7c5ba03a6c36.png">

**Comment by Wonsy** [comment]
Bien reçu, en attente de MEP.
