### ISSUE TITLE
Work as intented : Mauvais lien "trouves les lieux utiles..."

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#50]
@Wonsy :
**Bug** : Sur la "home page" avec le choix du thème, le bouton en bas "Trouve les lieux utiles à tes besoins" renvoie actuellement à la commande de box. Attention, même pour les utilisateurs qui ont + de 25 ans.
**Amélioration** : Prévoir une redirection sur l'écran "SOS à qui t'adresser" en attendant que le bon écran soit prêt.

**Comment by Wonsy** [comment]
@PerrineG : Vu, c'est modifié. Attention cependant, c'est un point qui a déjà été discuté lors de nos précédentes réunions et un "work as intended" également. Le bouton avait été mis en "raccourci" pour éviter d'avoir à faire les quizzs pour accéder à la commande de box.

Il n'avait pas été modifié depuis en raison du ticket #23 sur le même sujet.

Le lien vers "SOS" a été mis en place; en attente de MEP.

**Comment by PerrineG** [comment]
@Wonsy : merci pour ton retour. Effectivement on en a parlé plusieurs fois et tu nous avais expliqué le pourquoi, mais comme il n'y avait pas de ticket dessus, j'avais peur que ça parte aux oubliettes avant le lancement.
