### ISSUE TITLE
Retour UI : Modifier la typo des box

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#52]
@Wonsy :
Suite des tickets en lien avec les retours Figma :
Il faut modifier la typographie du nom des box sur l'écran de commande avec la liste des box.
Actuellement c'est la Chivo qui est affichée mais pour les sous-titres il faut utiliser la typo Abel (comme sur les cards des autres écrans).

**Comment by Wonsy** [comment]
@PerrineG : Vu, bien reçu. Au temps pour moi, c'est fixé; en attente de MEP.
