### ISSUE TITLE
Retour UI : Champs CP

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#61]
Lorsque l'on saisi un CP hors zone, le message "Aïe..." s'affiche correctement. Mais si on change de CP en mettant les bons, alors la croix pour fermer sort du champs (cf. capture).

![88098186_2856372997774755_9041489865610362880_n](https://user-images.githubusercontent.com/59702865/75763835-2f873600-5d3d-11ea-87e0-fbe16278906a.png)

**Comment by Wonsy** [comment]
Non reproduit pour le moment - en attente.
