### ISSUE TITLE
Zoning bouton "Réponse" sur réponse de quizz

### ISSUE THREAD

**Issue by Wonsy** [SocialGouv/tumeplay-app#66]
Overlap avec le "Plus d'infos"

**Comment by PerrineG** [comment]
@Wonsy : Quand le texte de la réponse est long (c'est à dire qu'il vient se mettre sous le bouton "suivant"), alors prévoir un scroll qui permet de lire tout le texte (cf. la card détail des box). La card garde la même taille.
> si besoin, je peux créer une maquette.

**Comment by Wonsy** [comment]
En attente MEP.
