### ISSUE TITLE
Back-office. Erreur d'affichage contenu des boîtes.

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#7]
Les box contiennent non seulement des produits du catalogue, mais aussi des contenus print qu'on ne peut pas ajouter directement à partir de la section "Boxs" du back-office.

On pourrait éventuellement les ajouter d'abord à la section "Produits" mais erreur d'ajout de produit (ticket#6).

**Comment by yowamuzadi** [comment]
@Wonsy

**Comment by Wonsy** [comment]
@yowamuzadi : À priori, le problème a été réglé avec la dernière MEP. Serait-il possible de me confirmer que tout est OK de votre coté ?

**Comment by yowamuzadi** [comment]
C'est bon, merci !
