### ISSUE TITLE
Affichage bonne/mauvaise réponse à modifier 

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#8]
@Wonsy

L'affichage de la bonne réponse a été modifié côté UI, à voir sur figma (section workflow macro, 4ème colonne)

**Comment by PerrineG** [comment]
Quand la réponse est mauvaise : <img width="232" alt="Capture d’écran 2020-01-28 à 10 13 42" src="https://user-images.githubusercontent.com/59702865/73250294-e4ff2080-41b6-11ea-8640-17266cd30486.png">
Quand la réponse est bonne : <img width="229" alt="Capture d’écran 2020-01-28 à 10 13 49" src="https://user-images.githubusercontent.com/59702865/73250295-e597b700-41b6-11ea-8bc6-4e178e6183bc.png">

**Comment by Wonsy** [comment]
Bonjour,
@PerrineG  & @yowamuzadi  : Fait, en attente de MEP.

**Comment by PerrineG** [comment]
Hello @Wonsy !
Suite à la discussion de ce matin, voici un essai avec la pastille "mauvaise réponse" remplie :
<img width="423" alt="Capture d’écran 2020-01-30 à 16 01 48" src="https://user-images.githubusercontent.com/59702865/73461144-f0e71000-4379-11ea-9b9d-fbd132ec23c2.png">
Nous pourrons le faire tester mardi pendant les tests utilisateurs avec @yowamuzadi . 
On peut voir pour l'intégrer et regarder s'il y a une grande différence ou non avec la pastille vide.

**Comment by Wonsy** [comment]
Hello,

Vu, en attente de MEP.
