### ISSUE TITLE
Retour UI : Lisibilité de la jauge pendant le quiz

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/tumeplay-app#80]
Quand on répond au quiz, on ne voit pas la jauge et donc les points augmenter.
On pourrait réduire un peu la pop-up du quiz, pour que la jauge apparaisse entièrement en haut et baisser l'opacité du fond noir (cf. maquette sur Figma et capture ici) : 

![quiz_jauge](https://user-images.githubusercontent.com/59702865/77448772-7a064a80-6df1-11ea-87e0-9346138ca039.jpg)

**Comment by yowamuzadi** [comment]
J'ai l'impression que le logo de la jauge de points sur la pré-prod n'est pas le même que celui qui figure sur la capture ci-jointe par @PerrineG
