### ISSUE TITLE
Vérifier le support du HTML dans les réponses de quizz

### ISSUE THREAD

**Issue by Wonsy** [SocialGouv/tumeplay-app#84]

**Comment by Wonsy** [comment]
Fait : les liens passent, comme le gras, cependant la police de caractère utilisée nécessite une graisse plus forte que celle de base ( 500 -> 700 ). En cours.

**Comment by Wonsy** [comment]
Fixé.

**Comment by yowamuzadi** [comment]
Ok pour moi :)
