### ISSUE TITLE
BO > Liaison des objets "Questions" du quiz aux objets "Contenu"

### ISSUE THREAD

**Issue by ViMotte** [SocialGouv/tumeplay-app#87]
Lier Contenus et Questions : à chaque Contenu correspond une Question du quiz :
 - Garder uniquement le menu Contenu, on retire le menu Quiz
 - Dans la page d'édition du contenu, éditer la question associée au contenu : 
     - Titre de la question
     - Réponses possibles et sélection de la bonne réponse
     - Visuel associé

Profiter de la refonte de la page d'édition d'un Contenu pour ajouter un champ "Commentaire", pour le moment sous la forme d'un champ de texte classique (cf. https://docs.google.com/spreadsheets/d/1s11YSZsRH7MFrYuGrZjAFxjG9F7mN0qCc6jR7fnhF1g/edit#gid=1105171542)

**Comment by yowamuzadi** [comment]
Testé de mon côté, tout est OK !
