### ISSUE TITLE
BO > Gestion des états d'un Contenu

### ISSUE THREAD

**Issue by ViMotte** [SocialGouv/tumeplay-app#88]
Création d'un champ "État" qui vient remplacer le champ "Publié". 

Etats possibles (pour l'instant sans règles logique de changement d'état) : 
 - Rédaction en cours
 - En attente de visuel
 - En attente de validation
 - Publié
 - Dépublié
 - Archivé (-> remplace la suppression d'un contenu ; ne pas afficher les contenus de cet état dans la liste sauf si spécifiquement demandé dans les filtres)

**Comment by yowamuzadi** [comment]
quand j'ai filtré sur "Les premières fois" + "a poils" j'avais quand même les contenus archivés qui apparaissaient dans la liste je ne sais pas si c'est un comportement prévu (dans le ticket il y a écrit que ces contenus n'apparaissent que si demandé) sinon tout est OK pour moi
