### ISSUE TITLE
Bouton "commander" dans le parcours d'achat 

### ISSUE THREAD

**Issue by yowamuzadi** [SocialGouv/tumeplay-app#9]
@Wonsy 

Le bouton "Commander" doit toujours être visible sur l'écran en "float"
Par exemple :
- Quand on clique sur la box "Découvre ton corps", on ne voit pas le bouton sauf si on descend en bas
- Même chose pour la boîte sur-mesure

**Comment by Wonsy** [comment]
@yowamuzadi : Bien reçu; en attente de MEP.
