### ISSUE TITLE
BO > Refonte de l'affichage de la liste de "Contenus"

### ISSUE THREAD

**Issue by ViMotte** [SocialGouv/tumeplay-app#90]
Ajouter les champs : 
 - "Id" : Id unique du contenu
 - "Sélectionner" : Checkbox de sélection du contenu 

Retirer les champs : 
 - "Date de création"
 - "Action"

Évolution globales :
 - Aller à l'édition d'un contenu en cliquant sur son titre 
 - Changer le champs "Publier" en "Etat"

Ajouter une barre d'outils en haut de la liste, avec les actions suivantes : 
 - "Ajouter" : Crée un nouveau contenu et envoie sur la page d'édition du nouveau contenu
 - "Filtrer" : permet de filtrer les contenus par (plusieurs choix sélectionnables): 
     - Thématique
     - Catégorie
     - Etat
 - "Etat" * : permet de changer l'état du contenu
 - "Archiver" * : passe l'état du contenu sélectionné en "Archivé" et le retire de la liste (remplace le mécanisme actuel de suppression)
 - "Dupliquer" * : duplique le(s) contenu(s) sélectionné(s) 
 - "Assigner à" * : permet de changer la thématique et/ou la catégorie associée au(x) contenu(s) sélectionné(s)

NB : * ces champs sont grisés par défaut et ne sont applicables que lorsqu'un ou plusieurs contenus ont été sélectionnés

**Comment by yowamuzadi** [comment]
tout fonctionne très bien ! RAS
