### ISSUE TITLE
Attribution des points du Quiz 

### ISSUE THREAD

**Issue by ViMotte** [SocialGouv/tumeplay-app#91]
Nombre de points attitrés par réponse : 
 - Un utilisateur qui a une réponse juste gagne 100 points
 - Un utilisateur qui a une réponse fausse gagne 25 points 
 - Un utilisateur qui répond « Je ne sais pas » gagne 30 points

Evolutions BO nécessaire : 
 - Permettre la catégorisation d'une réponse (radio button)
     - "Bonne réponse"
     - "Je ne sais pas"
     - "Mauvaise réponse" (ne pas afficher - par défaut si aucune des catégories précédente n'est sélectionnée)

**Comment by yowamuzadi** [comment]
quand je clique sur "Je ne sais pas" je gagne 25 points (au lieu de 30 comme prévu), le reste est ok 👍
